### ISSUE TITLE
Export as PDF

### ISSUE THREAD

**Issue by elgaspar** [elgaspar/Odot#2]
There is already the code to create the FlowDocument that is used for printing. That same FlowDocument should be converted to PDF. Further help, explanation will be given.

**Comment by scottharner** [comment]
I'd like to try my hand at this one. I'm looking to get my feet wet with open source contributions in general and github specifically. If you have any particular constraints on how you'd like it to be approached, let me know.

**Comment by elgaspar** [comment]
Hello, you can go on.
There is a class PrintDocument (in Views.Assist) that creates a FlowDocument object which is used to print the data. The ideal case would be that you could use the same FlowDocument object and just make a PDF out of it so printed doc and PDF file have the exact same look and styling.
If you need any help let me know.
Happy coding :)

**Comment by scottharner** [comment]
Any word on the pull request? I'm not sure how long these things typically take but let me know if i need to make any changes.

**Comment by elgaspar** [comment]
Oh, opened 19 days ago?
For some reason I had never seen it, have no idea why.
I am sorry! I will review it as soon as possible. Probably tommorow.

**Comment by scottharner** [comment]
Take your time. Thanks for responding back.
